# Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

def nparray_with_N_elements(N):
    
    x = np.arange(N - 1, -1, -1)
    return x

print(nparray_with_N_elements(5))
print(nparray_with_N_elements(10))
print(nparray_with_N_elements(15))

[4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


# Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
def diag_matrix(N):
    
    x = np.diag(np.arange(N, -1, -1)) # N включительно
    return x

matrix = diag_matrix(4)
print(matrix)
print('Сумма диагональных элементов: ', sum(np.diagonal(matrix)))

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Сумма диагональных элементов:  10


# Задание 3

Решите систему уравнений:               
4x + 2y + z = 4             
x + 3y = 12              
5y + 4z = -3            

In [5]:
x = np.array([[4, 2, 1], [1, 3, 0], [5, 0, 4]])
y = np.array([4, 12, -1])

In [6]:
def equation(x, y):
    
    answer = np.linalg.solve(x, y)
    return answer

answer = equation(x, y)
answer

array([-1.8,  4.6,  2. ])

In [7]:
np.allclose(np.dot(x, answer), y)

True

# Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [8]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [9]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [10]:
def find_best_resemblance(matrix, user):
    
    scalar = np.dot(matrix, user)
    norma_of_matrix = np.sqrt(np.sum(np.power(users_stats, 2), 1))
    norma_of_user = np.linalg.norm(user)
    cos_matrix_radian = np.arccos(scalar / norma_of_matrix / norma_of_user)
    best_resemblance = np.argmin(cos_matrix_radian)
    cos_in_degrees = round(cos_matrix_radian[7]*360/2/np.pi, 3)
    return f'Лучшим совпадением является покупатель под индексом {best_resemblance}. Угол между\
 ними {cos_in_degrees} градусов'
    
find_best_resemblance(users_stats, next_user_stats) 

'Лучшим совпадением является покупатель под индексом 7. Угол между ними 18.435 градусов'